### ISSUE TITLE
Cosmetic:round corners missing

### ISSUE THREAD

**Issue by hfroese** [disroot/dishub-themes#3]
In post status are some round corners missing:

![20180528-1110](https://user-images.githubusercontent.com/1968490/40607145-f4b69e16-6267-11e8-87a2-d1d8df74ad3c.jpg)

**Comment by hfroese** [comment]
Some more missing rounded corners:

![20180529-1359](https://user-images.githubusercontent.com/1968490/40657704-13a898f6-6349-11e8-811c-0be1ec4914e3.png)

**Comment by antil0pa** [comment]
I committed some fixes for the missing round corners. you can pull and check them :)
(the dropdown menu items like in the addon settings i left with rounded corners only on top.)

**Comment by hfroese** [comment]
Works perfect. Tanks :)
